# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ec9efa7784dbf79d4a2503009492ad7f"
application_url = "https://que-discovery-lady-viewers.trycloudflare.com"
embedded = true
name = "shoptimizer"
handle = "shoptimizer-1"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://que-discovery-lady-viewers.trycloudflare.com/auth/callback",
  "https://que-discovery-lady-viewers.trycloudflare.com/auth/shopify/callback",
  "https://que-discovery-lady-viewers.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "tiny-ninja-test.myshopify.com"
automatically_update_urls_on_dev = true
